# Generated by Django 4.2.7 on 2024-01-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='garment',
            new_name='garment_name',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='name',
            new_name='operation_name',
        ),
    ]
