# Generated by Django 4.2.7 on 2024-01-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_garment_operation_garment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='garment_name',
            new_name='garment',
        ),
    ]
