# Generated by Django 4.2.7 on 2024-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_garment_name_operation_garment'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='progress',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garment',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
