# Generated by Django 4.2.7 on 2024-02-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_garment_progress_garment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='garment',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
