# Generated by Django 4.2.7 on 2024-02-11 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_garment_progress_alter_garment_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('elapsed_time', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('progress_percentage', models.FloatField()),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garment')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operation')),
            ],
        ),
    ]
